name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      packages: read
      statuses: write

    steps:
      - name: Trigger Deploy Test
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        if: github.ref != 'refs/heads/main'
        with:
          owner: EGO-Tech
          repo: starbase-website
          workflow_file_name: deploy-to-ghpages.yml
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN  }}

      - name: Trigger Deploy
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        if: github.ref == 'refs/heads/main'
        with:
          owner: EGO-Tech
          repo: starbase-website
          workflow_file_name: deploy-to-ghpages.yml
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN  }}
          client_payload: '{"test": "false"}'
