---
name: YOLOL
on:
  push:
  pull_request:
    branches: [master]

permissions: {}

jobs:
  build:
    name: Validate YOLOL
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.17.3'
      - name: Setup yodk
        run: go install github.com/dbaumgarten/yodk@latest
      - name: Validate
        run: |
          yodk verify ./**/**/*.yolol
          yodk verify ./**/**/**/*.yolol
          yodk verify ./**/**/**/**/*.yolol
          yodk verify ./**/**/**/**/**/*.yolol
